hyp :
    giou: 3.54  
    cls: 37.4  
    cls_pw: 1.0 
    obj: 64.3  
    obj_pw: 1.0 
    iou_t: 0.225
    lr0: 0.00579
    lrf: -4.0  
    momentum: 0.937
    weight_decay: 0.000484
    fl_gamma: 0.5  
    hsv_h: 0.0138  
    hsv_s: 0.678  
    hsv_v: 0.36  
    degrees: 1.98  
    translate: 0.05 
    scale: 0.05  
    shear: 0.641  
epochs : 273
batch_size : 8
accumulate: 8
cfg : cfg/yolov3-spp.cfg
data : data/coco_mysplit.data
img_size : [416]
bucket : ''
weights : weights/yolov3-spp-ultralytics.pt
arc : default
darknet : default
name : ''
device : ''
working_dir : /A/andrey/yolo_ultra/weights
scheduler : multi-step
decay_steps : 0.8 0.9
gamma : 0.8