hyp :
    giou: 3.54  
    cls: 37.4  
    cls_pw: 1.0 
    obj: 64.3  
    obj_pw: 1.0 
    iou_t: 0.2
    lr0: 0.01
    lrf: -4.0  
    momentum: 0.937
    weight_decay: 0.000484
    fl_gamma: 0.5  
    hsv_h: 0.0138  
    hsv_s: 0.678  
    hsv_v: 0.36  
    degrees: 0.0
    translate: 0.0 
    scale: 0.0  
    shear: 0.0  
epochs : 300
batch_size : 8
accumulate: 8
cfg : cfg/exdark/yolov3.cfg
data : data/ExDark_train.data
img_size : [416]
bucket : ''
weights : ''
arc : default
darknet : default
name : ''
device : ''
working_dir : /A/andrey/yolo_compression/weights
scheduler : lambda
gamma : 0.8
early_stop: 75